cd vim-sensible
git pull
cd ../ctrlp.vim
git pull
cd ../nerdtree
git pull
cd ../python-mode
git pull
cd ../vim-nerdtree-tabs
git pull
cd ../nerdcommenter
git pull
cd ../vim-surround
git pull
cd ../syntastic
git pull
cd ../vim-airline
git pull
cd ../vim-airline-themes
git pull
cd ../vim-fugitive
git pull
cd ../vim-repeat
git pull
cd ../YouCompleteMe
git pull
git submodule update --init --recursive
cd ..
